ControlGastosWeb/Models/Presupuestos.cs
using System;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace ControlGastosWeb.Models
{
    public class Presupuestos
    {
        public int Id { get; set; }

        public string UsuarioId { get; set; }

        [Required]
        [Display(Name = "Tipo de Gasto")]
        public int TipoGastoId { get; set; }

        [Required]
        [Range(1, 12, ErrorMessage = "El mes debe estar entre 1 y 12.")]
        [Display(Name = "Mes")]
        public short Mes { get; set; }

        [Required]
        [Range(2000, 2100, ErrorMessage = "El año debe estar entre 2000 y 2100.")]
        [Display(Name = "Año")]
        public short Anio { get; set; }

        [Required]
        [Range(0.01, double.MaxValue, ErrorMessage = "El monto debe ser mayor que cero.")]
        [Display(Name = "Monto")]
        [DataType(DataType.Currency)]
        public decimal Monto { get; set; }

        [ForeignKey("TipoGastoId")]
        public virtual TipoGasto TipoGasto { get; set; }
    }
}

ControlGastosWeb/Controllers/PresupuestosController.cs
using ControlGastosWeb.Models;
using Microsoft.AspNet.Identity;
using System;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web.Mvc;
using System.ComponentModel.DataAnnotations.Schema;

namespace ControlGastosWeb.Controllers
{
    [Authorize]
    public class PresupuestosController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: Presupuestos
        public ActionResult Index()
        {
            if (!User.Identity.IsAuthenticated)
            {
                return RedirectToAction("Login", "Account");
            }

            //var userIdString = User.Identity.GetUserId();
            //Guid userId;
            var userId = User.Identity.GetUserId(); // string

            
            var presupuestos = db.Presupuestos
                .Include(p => p.TipoGasto)
                .Where(p => p.UsuarioId == userId)
                .OrderByDescending(p => p.Anio).ThenByDescending(p => p.Mes)
                .ToList();

            return View(presupuestos);
        }


        // GET: Presupuestos/Create
        // GET: Presupuestos/Create
        public ActionResult Create()
        {
            ViewBag.TiposGasto = db.TiposGasto.ToList();

            ViewBag.Mes = Enumerable.Range(1, 12)
                .Select(i => new SelectListItem
                {
                    Value = i.ToString(),
                    Text = new DateTime(1, i, 1).ToString("MMMM", new System.Globalization.CultureInfo("es-ES"))
                }).ToList();

            return View();
        }

        // POST: Presupuestos/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Presupuestos presupuesto)
        {
            if (ModelState.IsValid)
            {
                var userId = User.Identity.GetUserId();
                presupuesto.UsuarioId = userId;

                db.Presupuestos.Add(presupuesto);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.TiposGasto = db.TiposGasto.ToList();

            ViewBag.Mes = Enumerable.Range(1, 12)
                .Select(i => new SelectListItem
                {
                    Value = i.ToString(),
                    Text = new DateTime(1, i, 1).ToString("MMMM", new System.Globalization.CultureInfo("es-ES"))

                }).ToList();



            foreach (var modelError in ModelState)
            {
                foreach (var error in modelError.Value.Errors)
                {
                    System.Diagnostics.Debug.WriteLine($"Error en {modelError.Key}: {error.ErrorMessage}");
                }
            }

            return View(presupuesto);
        }

        // GET: Presupuestos/Edit/5
        public ActionResult Edit(int id)
        {
            var presupuesto = db.Presupuestos.Find(id);
            if (presupuesto == null)
            {
                return HttpNotFound();
            }

            ViewBag.TiposGasto = db.TiposGasto.ToList();

            var meses = Enumerable.Range(1, 12).Select(i => new SelectListItem
            {
                Value = i.ToString(),
                Text = new DateTime(1, i, 1).ToString("MMMM", new System.Globalization.CultureInfo("es-ES")),
            }).ToList();

            ViewBag.Mes = new SelectList(meses, "Value", "Text", presupuesto.Mes.ToString());

            return View(presupuesto);
        }

        // POST: Presupuestos/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(Presupuestos presupuesto)
        {
            if (ModelState.IsValid)
            {
                var userId = User.Identity.GetUserId();
                presupuesto.UsuarioId = userId;

                db.Entry(presupuesto).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.TiposGasto = db.TiposGasto.ToList();
            ViewBag.Mes = Enumerable.Range(1, 12)
                .Select(i => new SelectListItem
                {
                    Value = i.ToString(),
                    Text = i.ToString()
                }).ToList();

            return View(presupuesto);
        }

        // GET: Presupuestos/Delete/5
        public ActionResult Delete(int id)
        {
            var presupuesto = db.Presupuestos.Find(id);
            if (presupuesto == null)
            {
                return HttpNotFound();
            }
            return View(presupuesto);
        }

        // POST: Presupuestos/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            var presupuesto = db.Presupuestos.Find(id);
            db.Presupuestos.Remove(presupuesto);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

    }
}

ControlGastosWeb/Views/Presupuestos/Create.cshtml
@model ControlGastosWeb.Models.Presupuestos
@{
    ViewBag.Title = "Crear Presupuesto";
}

<style>
    body {
        background: linear-gradient(to bottom right, #2c3e50, #34495e);
        color: white;
    }

    .contenedor {
        margin-top: 60px;
        padding: 30px;
        background-color: rgba(255, 255, 255, 0.05);
        border-radius: 10px;
    }

    label {
        color: white;
    }

    .btn-naranja {
        background-color: #ff8c00;
        border-color: #ff8c00;
        color: white;
    }

        .btn-naranja:hover {
            background-color: #e67600;
        }

    .marca-agua {
        position: absolute;
        top: 60%;
        left: 50%;
        transform: translate(-50%, -50%);
        font-size: 100px;
        color: rgba(255, 255, 255, 0.03);
        pointer-events: none;
        user-select: none;
    }
</style>

<div class="container contenedor">
    <h2 class="text-center">Crear Presupuesto</h2>

    @if (!ViewData.ModelState.IsValid)
    {
        <div class="alert alert-danger">
            <ul>
                @foreach (var modelError in ViewData.ModelState.Values.SelectMany(v => v.Errors))
                {
                    <li>@modelError.ErrorMessage</li>
                }
            </ul>
        </div>
    }

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })

        <div class="row">
            <div class="col-md-4">
                <div class="form-group">
                    @Html.LabelFor(model => model.TipoGastoId, "Tipo de Gasto")
                    @Html.DropDownListFor(model => model.TipoGastoId, new SelectList(ViewBag.TiposGasto, "Id", "Descripcion"), "- Seleccione -", new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.TipoGastoId)
                </div>
            </div>

            <div class="col-md-4">
                <div class="form-group">
                    @Html.LabelFor(model => model.Monto)
                    @Html.TextBoxFor(model => model.Monto, new { @class = "form-control", type = "number", step = "0.01", min = "0" })
                    @Html.ValidationMessageFor(model => model.Monto)
                </div>
            </div>

            <div class="col-md-4">
                <div class="form-group">
                    @Html.LabelFor(model => model.Mes)
                    @Html.DropDownListFor(model => model.Mes, (IEnumerable<SelectListItem>)ViewBag.Mes, "- Seleccione Mes -", new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.Mes)
                </div>
            </div>
        </div>

        <div class="row">
            <div class="col-md-4">
                <div class="form-group">
                    @Html.LabelFor(model => model.Anio)
                    @Html.TextBoxFor(model => model.Anio, new { @class = "form-control", type = "number", min = "2023", max = DateTime.Now.Year })
                    @Html.ValidationMessageFor(model => model.Anio)
                </div>
            </div>
        </div>

        <div class="form-group text-center mt-3">
            <input type="submit" value="Guardar" class="btn btn-naranja" />
            @Html.ActionLink("Volver", "Index", null, new { @class = "btn btn-default" })
        </div>
    }

</div>

<div class="marca-agua">SMARTBIT</div>

ControlGastosWeb/Views/Presupuestos/Delete.cshtml
@model ControlGastosWeb.Models.Presupuestos

@{
    ViewBag.Title = "Eliminar Presupuesto";
}

<style>
    body {
        background: linear-gradient(to bottom right, #2c3e50, #34495e);
        color: white;
    }

    .form-container {
        margin-top: 60px;
        padding: 30px;
        background-color: rgba(255, 255, 255, 0.05);
        border-radius: 10px;
    }

    label {
        color: white;
    }

    .btn-naranja {
        background-color: #ff8c00;
        border-color: #ff8c00;
        color: white;
    }

        .btn-naranja:hover {
            background-color: #e67600;
        }

    .marca-agua {
        position: absolute;
        top: 60%;
        left: 50%;
        transform: translate(-50%, -50%);
        font-size: 100px;
        color: rgba(255, 255, 255, 0.03);
        pointer-events: none;
        user-select: none;
    }
</style>

<div class="container form-container">
    <h2 class="text-center">Eliminar Presupuesto</h2>

    <h4 class="text-center">¿Estás seguro que deseas eliminar este presupuesto?</h4>
    <hr />

    <dl class="dl-horizontal">
        <dt>Tipo de Gasto</dt>
        <dd>@Model.TipoGasto.Descripcion</dd>

        <dt>Mes</dt>
        <dd>@Model.Mes</dd>

        <dt>Año</dt>
        <dd>@Model.Anio</dd>

        <dt>Monto</dt>
        <dd>@Model.Monto</dd>
    </dl>

    @using (Html.BeginForm("Delete", "Presupuestos", FormMethod.Post))
    {
        @Html.AntiForgeryToken()
        @Html.HiddenFor(model => model.Id)

        <div class="form-group text-center">
            <input type="submit" value="Eliminar" class="btn btn-naranja" />
            @Html.ActionLink("Cancelar", "Index", null, new { @class = "btn btn-default" })
        </div>
    }
</div>

<div class="marca-agua">SMARTBIT</div>

ControlGastosWeb/Views/Presupuestos/Edit.cshtml
@model ControlGastosWeb.Models.Presupuestos
@{
    ViewBag.Title = "Editar Presupuesto";
}

<style>
    body {
        background: linear-gradient(to bottom right, #2c3e50, #34495e);
        color: white;
    }

    .contenedor {
        margin-top: 60px;
        padding: 30px;
        background-color: rgba(255, 255, 255, 0.05);
        border-radius: 10px;
    }

    label {
        color: white;
    }

    .btn-naranja {
        background-color: #ff8c00;
        border-color: #ff8c00;
        color: white;
    }

        .btn-naranja:hover {
            background-color: #e67600;
        }

    .marca-agua {
        position: absolute;
        top: 60%;
        left: 50%;
        transform: translate(-50%, -50%);
        font-size: 100px;
        color: rgba(255, 255, 255, 0.03);
        pointer-events: none;
        user-select: none;
    }
</style>

<div class="container contenedor">
    <h2 class="text-center">Editar Presupuesto</h2>

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()
        @Html.HiddenFor(model => model.Id)

        <div class="row">
            <div class="col-md-4">
                <div class="form-group">
                    @Html.LabelFor(model => model.TipoGastoId)
                    @Html.DropDownListFor(model => model.TipoGastoId, new SelectList(ViewBag.TiposGasto, "Id", "Descripcion", Model.TipoGastoId), "- Seleccione -", new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.TipoGastoId)
                </div>
            </div>

            <div class="col-md-4">
                <div class="form-group">
                    @Html.LabelFor(model => model.Monto)
                    @Html.TextBoxFor(model => model.Monto, new { @class = "form-control", type = "number", step = "0.01", min = "0" })
                    @Html.ValidationMessageFor(model => model.Monto)
                </div>
            </div>

            <div class="col-md-4">
                <div class="form-group">
                    @Html.LabelFor(model => model.Mes)
                    @Html.DropDownListFor(model => model.Mes, (IEnumerable<SelectListItem>)ViewBag.Mes, "- Seleccione Mes -", new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.Mes)
                </div>
            </div>
        </div>

        <div class="row">
            <div class="col-md-4">
                <div class="form-group">
                    @Html.LabelFor(model => model.Anio)
                    @Html.TextBoxFor(model => model.Anio, new { @class = "form-control", type = "number", min = "2023", max = DateTime.Now.Year })
                    @Html.ValidationMessageFor(model => model.Anio)
                </div>
            </div>
        </div>

        <div class="form-group text-center mt-3">
            <input type="submit" value="Guardar Cambios" class="btn btn-naranja" />
            @Html.ActionLink("Volver", "Index", null, new { @class = "btn btn-default" })
        </div>
    }

</div>

<div class="marca-agua">SMARTBIT</div>

ControlGastosWeb/Views/Presupuestos/Index.cshtml
@model IEnumerable<ControlGastosWeb.Models.Presupuestos>
@{
    ViewBag.Title = "Presupuestos";
}

<link rel="stylesheet" href="https://cdn.datatables.net/1.13.6/css/dataTables.bootstrap.min.css" />

<style>
    body {
        background: linear-gradient(to bottom right, #2c3e50, #34495e);
        color: white;
    }

    .contenedor {
        margin-top: 60px;
        padding: 30px;
        background-color: rgba(255, 255, 255, 0.05);
        border-radius: 10px;
    }

    table {
        background-color: white;
        color: black;
    }

    .btn-naranja {
        background-color: #ff8c00;
        border-color: #ff8c00;
        color: white;
    }

        .btn-naranja:hover {
            background-color: #e67600;
        }

    .marca-agua {
        position: absolute;
        top: 60%;
        left: 50%;
        transform: translate(-50%, -50%);
        font-size: 100px;
        color: rgba(255, 255, 255, 0.03);
        pointer-events: none;
        user-select: none;
    }
</style>

<div class="container contenedor">
    <h2 class="text-center">Presupuestos</h2>
    <p>
        @Html.ActionLink("Crear nuevo presupuesto", "Create", null, new { @class = "btn btn-naranja" })
    </p>

    <hr />

    <table id="tablaPresupuestos" class="table table-bordered table-hover">
        <thead class="table-dark">
            <tr>
                <th>Año</th>
                <th>Mes</th>
                <th>Tipo de Gasto</th>
                <th>Monto</th>
                <th>Acciones</th>
            </tr>
        </thead>
        <tbody>
            @if (Model.Any())
            {
                foreach (var item in Model)
                {
                    <tr>
                        <td>@item.Anio</td>
                        <td>@item.Mes</td>
                        <td>@item.TipoGasto.Descripcion</td>
                        <td>@item.Monto.ToString("C")</td>
                        <td>
                            @Html.ActionLink("Editar", "Edit", new { id = item.Id }, new { @class = "btn btn-sm btn-warning" }) |
                            @Html.ActionLink("Eliminar", "Delete", new { id = item.Id }, new { @class = "btn btn-sm btn-danger" })
                        </td>
                    </tr>
                }
            }
            else
            {
                
            }
        </tbody>
    </table>
    @section scripts {
        <!-- DataTables JS + Bootstrap 3 JS -->
        <script src="https://cdn.datatables.net/1.13.6/js/jquery.dataTables.min.js"></script>
        <script src="https://cdn.datatables.net/1.13.6/js/dataTables.bootstrap.min.js"></script>

        <script>
            $(document).ready(function () {
                $('#tablaPresupuestos').DataTable({
                    "language": {
                        "decimal": "",
                        "emptyTable": "No hay datos disponibles en la tabla",
                        "info": "Mostrando _START_ a _END_ de _TOTAL_ registros",
                        "infoEmpty": "Mostrando 0 a 0 de 0 registros",
                        "infoFiltered": "(filtrado de _MAX_ registros totales)",
                        "infoPostFix": "",
                        "thousands": ",",
                        "lengthMenu": "Mostrar _MENU_ registros",
                        "loadingRecords": "Cargando...",
                        "processing": "Procesando...",
                        "search": "Buscar:",
                        "zeroRecords": "No se encontraron registros coincidentes",
                        "paginate": {
                            "first": "Primero",
                            "last": "Último",
                            "next": "Siguiente",
                            "previous": "Anterior"
                        },
                        "aria": {
                            "sortAscending": ": activar para ordenar la columna ascendente",
                            "sortDescending": ": activar para ordenar la columna descendente"
                        }
                    },
                    "order": [],
                    "pageLength": 10
                });
            });
        </script>
    }
</div>

<div class="marca-agua">SMARTBIT</div>